"""Init

Revision ID: d190967cb5b8
Revises: 
Create Date: 2026-02-08 19:04:54.054852

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d190967cb5b8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("paper_records",
    sa.Column("fully_qualified_name", sa.String(length=255), nullable=False),
    sa.Column("paper_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("abstract_len", sa.Integer(), nullable=False),
    sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("indexing_reserved_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("fully_qualified_name")
    )
    op.create_index("idx_papers_queue", "paper_records", ["abstract_len"], unique=False, postgresql_where=sa.text("indexed_at IS NULL AND indexing_reserved_at IS NULL"))
    op.create_table("sync_state",
    sa.Column("source", sa.String(length=255), nullable=False),
    sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("source")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_state")
    op.drop_index("idx_papers_queue", table_name="paper_records", postgresql_where=sa.text("indexed_at IS NULL AND indexing_reserved_at IS NULL"))
    op.drop_table("paper_records")
    # ### end Alembic commands ###
